# --- CONFIGURATIONS --- #
server:
  port: 8082

spring:
  application:
    name: course-service

  output:
    ansi:
      enabled: ALWAYS

  profiles:
    acrive:
      - dev
      - default

  devtools:
    restart:
      poll-interval: 1s

  # --- MongoDB --- #
  data:
    mongodb:
      database: Users
      host: localhost
      port: 27017
#      username: ""
#      password: ""

# --- Swagger --- #
swagger:
  meta:
    description: Documentation API of course service
    contact:
      name: FDP ASIS
      url: https://github.com/FDP-ASIS
      email: finalprojectafeka2020@gmail.com
    license:
      name: Afeka license
      url: ""
    version: 1.0.0

# --- Logger --- #
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: trace
