# --- CONFIGURATIONS --- #
repo: https://api.github.com/repos/FDP-ASIS/Repository

server:
  port: 8083

spring:
  application:
    name: software-service

  output:
    ansi:
      enabled: ALWAYS

  profiles:
    acrive:
      - dev

  devtools:
    restart:
      poll-interval: 1s

  # --- MongoDB --- #
  data:
    mongodb:
      database: FDP
      host: localhost
      port: 27017
#      username: ""
#      password: ""

# --- Logger --- #
logging:
  level:
    org.springframework.data.mongodb: TRACE
    org.springframework.web.servlet.mvc.method.annotation: TRACE

# --- Swagger --- #
swagger:
  meta:
    description: Documentation API of software service
    contact:
      name: FDP ASIS
      url: https://github.com/FDP-ASIS
      email: finalprojectafeka2020@gmail.com
    license:
      name: Afeka license
      url: ""
    version: 1.0.0

# --- Eureka --- #
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
