# --- CONFIGURATIONS --- #

server:
  port: 8081

spring:
  application:
    name: user-service

  output:
    ansi:
      enabled: ALWAYS

  profiles:
    active:
      - dev

  devtools:
    restart:
      poll-interval: 1s

  # --- MongoDB --- #
  data:
    mongodb:
      database: FDP
      host: localhost
      port: 27017

      #      username: ""
      #      password: ""

# --- Logger --- #
logging:
  level:
    org.springframework.data.mongodb: TRACE
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# --- Swagger --- #
swagger:
  meta:
    description: Documentation API of user service
    contact:
      name: FDP ASIS
      url: https://github.com/FDP-ASIS
      email: finalprojectafeka2020@gmail.com
    license:
        name: Afeka license
        url: ""
    version: 1.0.0

# --- Eureka --- #
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/